### ISSUE TITLE
Creating a run configuration fails with contradictory error message

### ISSUE THREAD

**Issue by trejkaz** [JetBrains/gradle-idea-ext-plugin#10]
I tried to set up a run configuration to be automatically created:

```
idea {
  project {
    settings {
      runConfigurations {

        'Desktop Test'(Application) {
          mainClass = 'com.acme.main.DesktopMain'
          moduleName = getProject(':main').idea.module.name
          workingDirectory = rootDir
          jvmArgs = '...'
          envs = ext.environmentVars
        }

      }
    }
  }
}
```

But when I try to sync the project, I get a confusing error message:

> Cannot create a Application because this type is not known to this container. Known types are: Application, JUnit, Remote

**Comment by nskvortsov** [comment]
Unfortunately, this requires an import statement at the moment:

> import org.jetbrains.gradle.ext.*

**Comment by deepy** [comment]
I met with the same issue in #3

And it seems you are also missing the imports, try adding `import org.jetbrains.gradle.ext.*`

**Comment by trejkaz** [comment]
Argh... OK. I'm used to plugins just working and only having to import when I'm doing something weird.

**Comment by nskvortsov** [comment]
GIven how frustrating this error is, I'm thinking about renaming run configurations to something not clashing with Gradle's types.

**Comment by trejkaz** [comment]
Even just taking a string for it would almost be very gradle-like... or somehow making it a method which is available in the right context.

```
...
      runConfigurations {

        application('Desktop Test') {
          ...
        }
...
```

**Comment by trejkaz** [comment]
Ah. It could just be that runConfigurations is too new to import in 2018.1.4, but even though it's legal, IDEA doesn't currently create the run config. Wait for the next update to IDEA?

**Comment by nskvortsov** [comment]
anything in DSL v0.1 should work in 2018.1 
would you mind sharing idea.log  +  the script you are importing?

**Comment by trejkaz** [comment]
The idea part of the build script itself is more or less what I posted in the original post.

```
idea {
  project {
    settings {
      runConfigurations {

        'Desktop Test'(org.jetbrains.gradle.ext.Application) {
          mainClass = 'com.acme.main.DesktopMain'
          moduleName = project(':main').idea.module.name
          workingDirectory = rootDir
          jvmArgs = '...'
          envs = project.ext.environmentVars
        }

      }
    }
  }
}
```

Logs for when I run the refresh operation. There is some chatter but nothing looks specifically like an error importing the project.

```
2018-06-08 08:12:33,215 [86283072]   INFO - s.plugins.gradle.GradleManager - Instructing gradle to use java from /Users/tester/DevEnv/Java/jdk1.8.0_92.jdk/Contents/Home 
2018-06-08 08:12:33,216 [86283073]   INFO - s.plugins.gradle.GradleManager - Instructing gradle to use java from /Users/tester/DevEnv/Java/jdk1.8.0_92.jdk/Contents/Home 
2018-06-08 08:12:33,236 [86283093]   INFO - xecution.GradleExecutionHelper - Passing command-line args to Gradle Tooling API: -Didea.version=2018.1.4 -Didea.resolveSourceSetDependencies=true --init-script /private/var/folders/d5/p7yfxkhx4673nd7z7lz_t36c0000gn/T/ijinit.gradle 
2018-06-08 08:12:39,702 [86289559]   INFO - s.log.data.VcsLogRefresherImpl - Not enough first block 
com.intellij.vcs.log.data.VcsLogRefreshNotEnoughDataException: Not enough first block
	at com.intellij.vcs.log.data.VcsLogJoiner.getFirstUnTrackedIndex(VcsLogJoiner.java:104)
	at com.intellij.vcs.log.data.VcsLogJoiner.getNewCommitsAndSavedGreenIndex(VcsLogJoiner.java:89)
	at com.intellij.vcs.log.data.VcsLogJoiner.addCommits(VcsLogJoiner.java:51)
	at com.intellij.vcs.log.data.VcsLogRefresherImpl$MyRefreshTask.join(VcsLogRefresherImpl.java:323)
	at com.intellij.vcs.log.data.VcsLogRefresherImpl$MyRefreshTask.doRefresh(VcsLogRefresherImpl.java:255)
	at com.intellij.vcs.log.data.VcsLogRefresherImpl$MyRefreshTask.run(VcsLogRefresherImpl.java:226)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-06-08 08:12:39,709 [86289566]   INFO - s.log.data.VcsLogRefresherImpl - Not enough first block 
com.intellij.vcs.log.data.VcsLogRefreshNotEnoughDataException: Not enough first block
	at com.intellij.vcs.log.data.VcsLogJoiner.getFirstUnTrackedIndex(VcsLogJoiner.java:104)
	at com.intellij.vcs.log.data.VcsLogJoiner.getNewCommitsAndSavedGreenIndex(VcsLogJoiner.java:89)
	at com.intellij.vcs.log.data.VcsLogJoiner.addCommits(VcsLogJoiner.java:51)
	at com.intellij.vcs.log.data.VcsLogRefresherImpl$MyRefreshTask.join(VcsLogRefresherImpl.java:323)
	at com.intellij.vcs.log.data.VcsLogRefresherImpl$MyRefreshTask.doRefresh(VcsLogRefresherImpl.java:255)
	at com.intellij.vcs.log.data.VcsLogRefresherImpl$MyRefreshTask.run(VcsLogRefresherImpl.java:226)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-06-08 08:12:50,398 [86300255]   INFO -  #git4idea.commands.GitHandler - git log took 10757 ms. Command parameters: 
/usr/bin/git -c core.quotepath=false -c log.showSignature=false -c diff.renameLimit=1000 log --no-walk=unsorted --stdin --pretty=format:%x01%x01%H%x02%ct%x02%an%x02%at%x02%ae%x02%cn%x02%ce%x02%P%x02%s%x02%b%x02%B%x03%x03 --encoding=UTF-8 -M --name-status -m -- 
2018-06-08 08:12:50,721 [86300578]   INFO -  #git4idea.commands.GitHandler - git log took 11064 ms. Command parameters: 
/usr/bin/git -c core.quotepath=false -c log.showSignature=false -c diff.renameLimit=1000 log --no-walk=unsorted --stdin --pretty=format:%x01%x01%H%x02%ct%x02%an%x02%at%x02%ae%x02%cn%x02%ce%x02%P%x02%s%x02%b%x02%B%x03%x03 --encoding=UTF-8 -M --name-status -m -- 
2018-06-08 08:12:51,622 [86301479]   INFO - agnostic.FrequentEventDetector - Too many events posted, #6. Event: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=TransferToEDTQueue[Multiple builds view queue],notifier=null,catchExceptions=false,when=1528413171622] on sun.lwawt.macosx.LWCToolkit@19f8b33d 
2018-06-08 08:12:51,816 [86301673]   INFO - agnostic.FrequentEventDetector - Too many events posted, #6. Event: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=TransferToEDTQueue[Multiple builds view queue],notifier=null,catchExceptions=false,when=1528413171815] on sun.lwawt.macosx.LWCToolkit@19f8b33d 
2018-06-08 08:12:51,885 [86301742]   INFO - agnostic.FrequentEventDetector - Too many events posted, #6. Event: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=TransferToEDTQueue[Multiple builds view queue],notifier=null,catchExceptions=false,when=1528413171885] on sun.lwawt.macosx.LWCToolkit@19f8b33d 
2018-06-08 08:12:51,955 [86301812]   INFO - agnostic.FrequentEventDetector - Too many events posted, #1. Event: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=TransferToEDTQueue[BuildTreeConsoleView later invocator],notifier=null,catchExceptions=false,when=1528413171955] on sun.lwawt.macosx.LWCToolkit@19f8b33d 
2018-06-08 08:12:52,032 [86301889]   INFO - agnostic.FrequentEventDetector - Too many events posted, #6. Event: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=TransferToEDTQueue[Multiple builds view queue],notifier=null,catchExceptions=false,when=1528413172032] on sun.lwawt.macosx.LWCToolkit@19f8b33d 
2018-06-08 08:12:52,095 [86301952]   INFO - agnostic.FrequentEventDetector - Too many events posted, #6. Event: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=TransferToEDTQueue[Multiple builds view queue],notifier=null,catchExceptions=false,when=1528413172095] on sun.lwawt.macosx.LWCToolkit@19f8b33d 
2018-06-08 08:12:52,167 [86302024]   INFO - agnostic.FrequentEventDetector - Too many events posted, #1. Event: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=TransferToEDTQueue[BuildTreeConsoleView later invocator],notifier=null,catchExceptions=false,when=1528413172167] on sun.lwawt.macosx.LWCToolkit@19f8b33d 
2018-06-08 08:13:55,044 [86364901]   INFO - xecution.GradleExecutionHelper - Passing command-line args to Gradle Tooling API: -Didea.version=2018.1.4 -Didea.resolveSourceSetDependencies=true --init-script /private/var/folders/d5/p7yfxkhx4673nd7z7lz_t36c0000gn/T/ijinit.gradle -Didea.version=2018.1.4 -Didea.resolveSourceSetDependencies=true --init-script /private/var/folders/d5/p7yfxkhx4673nd7z7lz_t36c0000gn/T/ijinit5.gradle 
2018-06-08 08:14:07,943 [86377800]   INFO - pl.ProjectRootManagerComponent - project roots have changed 
2018-06-08 08:14:08,169 [86378026]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 104ms; general responsiveness: ok; EDT responsiveness: ok 
2018-06-08 08:14:08,276 [86378133]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 106ms; general responsiveness: ok; EDT responsiveness: ok 

```

**Comment by nskvortsov** [comment]
Thank you. Indeed, nothing suspicious here. Do you have any customization in IDEA registry? (ctrl-shift-a -> "Registry") Check the value for `external.system.configuration.import.enabled` (should be `true`)

**Comment by trejkaz** [comment]
Apparently it's set to `true`.

**Comment by trejkaz** [comment]
I put the exact same configuration (class name changed) into another project, and the run configuration does get created for that one. So I guess now I'm binary-deleting bits of our real project until it works, to figure out where the difference is.

**Comment by trejkaz** [comment]
OK, I figured that out.

We had:

    ext.environmentVars['DYLD_FRAMEWORK_PATH'] = files(
      "/some/path",
    )

Which apparently worked fine for Gradle itself, but after I changed it to this:

    ext.environmentVars['DYLD_FRAMEWORK_PATH'] = files(
      "/some/path",
    ).asPath

The run config is now created properly. If the first syntax isn't permitted, I guess it should probably raise an error, otherwise it takes a long time to figure out what the problem is. :(

Anyway, next problem - I'm doing this:

          moduleName = project(':application').idea.module.name

This returns "application", but I really want it to return "application_main", if and only if the user is importing the IDEA project as one module per source root. Is there a way?

**Comment by nskvortsov** [comment]
This is no stable API to provide this, but you can refer to a system property as a workaround:
> def isPerSourceSet = System.properties.'idea.resolveSourceSetDependencies' as boolean

**Comment by nskvortsov** [comment]
thank you for digging through the env vars related issue. I will improve error logging, so that such issues are easier to detect.

**Comment by trejkaz** [comment]
System property works well enough for me. Got a lot of code in the area building the run configs anyway, due to all the similarity between them. Converting things over to this style will actually clean things up, while also resolving old issues about how to have different run configs per-platform.

**Comment by trejkaz** [comment]
Newer IDEA has a new setting:

Group modules using (  ) explicit module groups  (  ) using qualified names

Because qualified names are apparently the default, some developers here have started using it - but it breaks run configurations, because the name of modules changes.

Is there a similar system property to detect that setting, so that the run configs can generate the right names for the module?

Better yet, is there a way to avoid having to guess the name of the module when creating a run configuration?
